# Generated by Django 2.2.4 on 2020-05-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='jobrole',
            field=models.CharField(default='Web Developer', max_length=100),
            preserve_default=False,
        ),
    ]
