# Generated by Django 3.0.6 on 2020-06-12 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_jobrole'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='jobrole',
            new_name='goal',
        ),
    ]
