# Generated by Django 3.0.6 on 2020-06-19 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_profile_last_time_logou'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='last_time_logou',
            new_name='last_time_logout',
        ),
    ]
