# Generated by Django 3.0.4 on 2020-05-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Assigned', 'Assigned'), ('YES', 'Completed'), ('NO', 'NOt completed')], default='assigned', max_length=10),
        ),
    ]
