# Generated by Django 3.0.6 on 2020-06-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200609_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='work_done',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='work_today',
            field=models.CharField(max_length=500),
        ),
    ]
