# Generated by Django 3.0.6 on 2020-06-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200612_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default='Web Developer', max_length=30),
            preserve_default=False,
        ),
    ]
