# Generated by Django 3.0.6 on 2020-06-13 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_team_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Views',
        ),
    ]
