# Generated by Django 3.0.6 on 2020-06-16 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_delete_views'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
